name: Test release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # to create releases

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
    - name: Create draft release
      run: |
        gh release create ${{ env.TAG }} --draft --latest=false --generate-notes

